spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never

logging:
  level:
    root: WARN                     # 프로덕션에서는 경고 이상만 로깅
    com.my.investment_mentor: WARN # 애플리케이션 로그는 INFO 수준
    org.springframework: WARN      # Spring 로그는 경고 이상만

app:
  server:
    test:
      load-test:
        enabled: true
  frontend:
    url: https://moatickets.dev
  cookie:
    domain: moatickets.dev