spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  web:
    resources:
      add-mappings: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - profile
              - email
  jwt:
    secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}

toss:
  secret-key: ${TOSS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,env

app:
  server:
    scheduler:
      session_start: true
      ticket_release: true
  ai:
    url: ${AI_URL}

alarm:
  sender: sse