spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  web:
    resources:
      add-mappings: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - profile
              - email
  jwt:
    secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}

toss:
  secret-key: ${TOSS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,env
  metrics:
    distribution:
      percentiles-histogram:
        alarm.sse.send.seconds: true

app:
  server:
    alarm:
      type: ${APP_SERVER_ALARM:SSE}
      shard-count: 8
    scheduler:
      session-start:
        enabled: ${APP_SERVER_SCHEDULER_SESSION_START_ENABLED:true}
        delay: ${APP_SERVER_SCHEDULER_SESSION_START_DELAY:2}
        batch-size: ${APP_SERVER_SCHEDULER_SESSION_START_BATCH_SIZE:200}
        loop-count: ${APP_SERVER_SCHEDULER_SESSION_START_LOOP_COUNT:5}
      ticket-release:
        enabled: ${APP_SERVER_SCHEDULER_TICKET_RELEASE_ENABLED:true}
        delay: ${APP_SERVER_SCHEDULER_TICKET_RELEASE_DELAY:2}
        batch-size: ${APP_SERVER_SCHEDULER_TICKET_RELEASE_BATCH_SIZE:200}
        loop-count: ${APP_SERVER_SCHEDULER_TICKET_RELEASE_LOOP_COUNT:5}
        page-limit: ${APP_SERVER_SCHEDULER_TICKET_RELEASE_PAGE_LIMIT:200}
  ai:
    url: ${AI_URL}
  frontend:
    url: ${APP_FRONTEND_URL}
  cookie:
    domain: ${APP_COOKIE_DOMAIN}