spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: debug

app:
  frontend:
    url: http://localhost:5173
  ai:
    url: ${AI_URL}